try:
    pass
except:  # 全てを受け取ってしまうので明示的に記載する
    pass

# ------

try:
    pass
except Exception:
    pass
